Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  SecurityGroupStackName:
    Description: Security Group Stack Name
    Type: String
    MinLength: '1'
    MaxLength: '255'    
Resources:
  DevInstance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-055943271915205db
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !ImportValue 
          Fn::Sub: '${SecurityGroupStackName}-EC2HTTPSecurityGroup'
      SubnetId: 
        !ImportValue
        Fn::Sub: '${SecurityGroupStackName}-DevSubnetId'
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt update -y
            apt install apache fail2ban -y
      Tags:
        - Key: Name
          Value: Dev-Server
  
Outputs:
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - DevInstance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - DevInstance
      - PublicIp
