# This is a basic workflow to help you get started with Actions

name: deploy_aws
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-stack:
    runs-on: ubuntu-latest
    env:
      STACK_NAME: "sol-stack"  # Define stack name as a variable
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1  
      - name: Check if Stack Exists
        run: |
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].StackStatus" --output text --no-paginate || echo "STACK_NOT_FOUND")
          if [ "$STATUS" == "STACK_NOT_FOUND" ]; then
            echo "Stack does not exist, proceeding to create a new stack."
          else
            echo "Stack exists with status: $STATUS"
            if [ "$STATUS" == "DELETE_IN_PROGRESS" ]; then
              echo "Stack is being deleted, please wait until the delete process is complete."
              exit 1
            fi
            if [ "$STATUS" == "ROLLBACK_COMPLETE" ]; then
              echo "Stack is in ROLLBACK_COMPLETE state. Deleting the stack..."
              aws cloudformation delete-stack --stack-name "$STACK_NAME"
              aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
            fi
          fi
  deploy-networking:
    runs-on: ubuntu-latest
    needs: check-stack
    env:
      STACK_NAME: "sol-stack"  # Define stack name as a variable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1  
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name "$STACK_NAME" \
            --template-file cloud-formation/deploy-network.yml \
            --capabilities CAPABILITY_NAMED_IAM
  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-networking
    env:
      STACK_NAME: "sol-stack-server"  # Define stack name as a variable

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1  
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name "$STACK_NAME" \
            --template-file cloud-formation/deploy-servers.yml \
            --capabilities CAPABILITY_NAMED_IAM